server:
  port: 8864
  context-path: /cmfz
  jsp-servlet:
    init-parameters:
      develoment: true
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cmfz
  mvc:
    view:
      prefix: /
      suffix: .jsp
  http:
    encoding:
      charset: UTF-8
      force: true
mybatis:
  type-aliases-package: com.baizhi.cmfz.entity
  #加载mapper文件
  mapper-locations: classpath:/com/baizhi/cmfz/dao/*DAOMapper.xml